version: "3.7"
services:
  app:
    build:
      target: dev
      args:
        PM: ${PM:-npm}
        BUILD_ENV: ${BUILD_ENV:-development}
        NODE_ENV: ${NODE_ENV}
    command: >
      /bin/ash -c "
        bin/docker/watch
      "
    # command: >
    #   /bin/ash -c "
    #     bin/helper/wait ${DB_HOST}:${DB_PORT};
    #     bin/docker/watch
    #   "
    environment:
      WATCH_CMD: "${WATCH_CMD}"
      HOSTNAME_CUSTOM: "${HOSTNAME_CUSTOM}"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.yarn
