# entr
FROM lagden/entr:4.7-alpine3.13 as entr
LABEL autodelete="true"
LABEL maintainer="lagden@gmail.com"

# -----

FROM node:14.16-alpine3.13
LABEL maintainer="lagden@gmail.com"

# If Docker Host is Mac or Windows
ENV ENTR_INOTIFY_WORKAROUND=1
COPY --from=entr /usr/local/bin/entr /usr/local/bin/.

# Shared libraries
RUN apk add --no-cache --update libc6-compat
RUN ln -s /lib64/ld-linux-x86-64.so.2 /lib/ld-linux-x86-64.so.2

# Timezone
RUN apk add --no-cache --update tzdata
ENV TZ=America/Sao_Paulo
RUN ln -s /usr/share/zoneinfo/$TZ /etc/localtime

# Clear apk cache
RUN rm -rf /var/cache/apk/*

# Yarn 2
RUN yarn set version berry

ARG NODE_ENV="production"
ARG BASE="/home/node"

ENV NODE_ENV=$NODE_ENV
ENV BASE=$BASE
ENV BASE_APP=$BASE/app

WORKDIR $BASE
ADD --chown=node:node . $BASE_APP

USER node

WORKDIR $BASE_APP
