version: "3.7"
services:
  app:
    build:
      dockerfile: ${DOCKERFILE}
      context: ./
      args:
        NODE_ENV: ${NODE_ENV}
    command: >
      /bin/ash -c "
        bin/watch
      "
    environment:
      WATCH_CMD: "${WATCH_CMD}"
      HOSTNAME_CUSTOM: "${HOSTNAME_CUSTOM}"
    volumes:
      - .:/home/node/app
