version: "3.9"
services:
  app:
    build:
      target: dev
      args:
        PM: ${PM:-npm}
        NODE_ENV: ${NODE_ENV}
    command: >
      /bin/ash -c "
        ${WATCH_CMD}
      "
    # command: >
    #   /bin/ash -c "
    #     bin/helper/wait ${DB_HOST}:${DB_PORT};
    #     ${WATCH_CMD}
    #   "
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
