version: "3.9"
services:
  app:
    image: ${REGISTRY}/${IMAGE}:${VERSION:-local}
    command: ${RUN_CMD}
    environment:
      DEBUG_HIDE_DATE: ${DEBUG_HIDE_DATE}
      DEBUG_COLORS: ${DEBUG_COLORS}
      DEBUG_PREFIX: ${DEBUG_PREFIX}
      DEBUG: ${DEBUG}
      NODE_ENV: ${NODE_ENV}
      APP_ENV: ${APP_ENV}
      APP_NS: ${APP_NS}
      PORT: ${PORT}
      VERSION: ${VERSION:-local}
      HOSTNAME_CUSTOM: "${HOSTNAME_CUSTOM:-127.0.0.1}"
      # coloque suas variáveis
      # ...
    ports:
      - ${PORT}:${PORT}
