version: "3.7"
services:
  app:
    image: ${REGISTRY}/${IMAGE}:${VERSION}
    command: >
      /bin/ash -c "
        node server
      "

    # command: >
    #   /bin/ash -c "
    #     npx sirv ${PUBLIC_DIR} --dev -eBc -m 0 -H ${HOSTNAME_CUSTOM} --port ${PORT}
    #   "

    # command: >
    #   /bin/ash -c "
    #     bin/helper/wait ${DB_HOST}:${DB_PORT};
    #     node server
    #   "

    environment:
      DEBUG_HIDE_DATE: ${DEBUG_HIDE_DATE}
      DEBUG_COLORS: ${DEBUG_COLORS}
      DEBUG_PREFIX: ${DEBUG_PREFIX}
      DEBUG: ${DEBUG}
      NODE_ENV: ${NODE_ENV}
      APP_ENV: ${APP_ENV}
      APP_NS: ${APP_NS}
      PORT: ${PORT}
      PORT_PUBLISHED: ${PORT_PUBLISHED}
      VERSION: ${VERSION}
      HOSTNAME_CUSTOM: "${HOSTNAME_CUSTOM}"
      # coloque mais envs...
    ports:
      - ${PORT_PUBLISHED}:${PORT}
    networks:
      - net
    deploy:
      mode: replicated
      replicas: ${DEPLOY_REPLICAS}
      resources:
        limits:
          cpus: ${DEPLOY_RESOURCES_LIMITS_CPUS}
          memory: ${DEPLOY_RESOURCES_LIMITS_MEMORY}
      restart_policy:
        condition: on-failure
        delay: ${DEPLOY_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${DEPLOY_RESTART_POLICY_MAX_ATTEMPTS:-3}

networks:
  net:
    name: ${NETWORK_NAME}

# volumes:
#   db:
#     name: ${VOL_NAME}_db
