version: "3.9"
services:
  app:
    image: ${REGISTRY}/${IMAGE}:${VERSION}
    command: ${RUN_CMD}
    environment:
      DEBUG_HIDE_DATE: ${DEBUG_HIDE_DATE}
      DEBUG_COLORS: ${DEBUG_COLORS}
      DEBUG_PREFIX: ${DEBUG_PREFIX}
      DEBUG: ${DEBUG}
      NODE_ENV: ${NODE_ENV}
      APP_ENV: ${APP_ENV}
      APP_NS: ${APP_NS}
      PORT: ${PORT}
      PORT_PUBLISHED: ${PORT_PUBLISHED}
      VERSION: ${VERSION}
      HOSTNAME_CUSTOM: "${HOSTNAME_CUSTOM}"
      # coloque mais envs...
    ports:
      - ${PORT_PUBLISHED}:${PORT}
    networks:
      - net
    deploy:
      replicas: ${DEPLOY_REPLICAS}
      resources:
        limits:
          cpus: ${DEPLOY_RESOURCES_LIMITS_CPUS}
          memory: ${DEPLOY_RESOURCES_LIMITS_MEMORY}
      restart_policy:
        condition: on-failure
        delay: ${DEPLOY_RESTART_POLICY_DELAY:-5s}

networks:
  net:
    name: ${NETWORK_NAME}

# volumes:
#   db:
#     name: ${VOL_NAME}_db
