# entr
FROM lagden/entr:4.7-alpine3.13 as entr
LABEL autodelete="true"
LABEL maintainer="lagden@gmail.com"

# -----

FROM node:14.16-alpine3.13
LABEL maintainer="lagden@gmail.com"

# If Docker Host is Mac or Windows
ENV ENTR_INOTIFY_WORKAROUND=1

# Timezone
RUN apk add --no-cache tzdata
ENV TZ=America/Sao_Paulo
RUN ln -s /usr/share/zoneinfo/$TZ /etc/localtime

RUN ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2
COPY --from=entr /usr/local/bin/entr /usr/local/bin/.

ARG NODE_ENV="production"
ARG BASE="/home/node"

ENV NODE_ENV=$NODE_ENV
ENV BASE=$BASE
ENV BASE_APP=$BASE/app

WORKDIR $BASE
ADD --chown=node:node . $BASE_APP

WORKDIR $BASE_APP
RUN npm ci --ignore-scripts --also=dev
RUN npm rb node-sass
RUN npm run build

USER node
